#!/bin/bash

#       Building on Linux.  Note: only compiles in OGG and MP3 support
#       if the libraries are already setup within libs/, otherwise
#       omits them.  To build the libraries, see the 'mk-libmad-linux'
#       and 'mk-tremor-linux' scripts.

OPT="-DT_LINUX_ALSA -Wall -g  -lm -lpthread  `pkg-config --cflags alsa` -DOGG_DECODE" 
LIBS="`pkg-config --libs alsa` `pkg-config --libs vorbisfile`"

echo $OPT $LIBS


# [ -f libs/linux-libmad.a ] && {
#     OPT="-DMP3_DECODE $OPT"
#     LIBS="$LIBS libs/linux-libmad.a"
# }
# [ -f libs/linux-libvorbisidec.a ] && {
#     OPT="-DOGG_DECODE $OPT"
#     LIBS="$LIBS libs/linux-libvorbisidec.a"
# }


gcc $OPT sbagen.c $LIBS -o sbagen || exit 1

