#!/bin/sh

# This script should be run under MinGW/MSYS.  Both the configure and
# the make will fail, but this sets up enough to build the rest.  You
# should run this in the libmad* directory that was created when you
# downloaded and unpacked the archive from the libmad site:
#
#   http://www.underbit.com/products/mad/
#

# ** Both of these will fail
./configure --host=mingw32 
make 

echo ""

OPT="-DHAVE_CONFIG_H -I. -I. -I. -DFPM_INTEL -DASO_ZEROCHECK -Wall -g -O -fforce-mem -fforce-addr -fthread-jumps -fcse-follow-jumps -fcse-skip-blocks -fexpensive-optimizations -fregmove -fschedule-insns2 -fstrength-reduce -c"

for xx in version.c fixed.c bit.c timer.c stream.c frame.c \
		    synth.c decoder.c layer12.c layer3.c huffman.c
do
    echo == $xx
    gcc $OPT $xx || exit 1
done

ar rv libmad.a *.o





